context:
  name: renode-cores
  version: "1.15.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/renode/renode/releases/download/v${{ version }}/renode_${{ version }}_source.tar.xz
    sha256: 40c50afe8db86a9c63f4a86b93116a6babd43bf241cfaac47b2c0d2cbc2b15a8
  - url: https://github.com/renode/renode-infrastructure/archive/3fc2d5fe643068e595e875d9408cb4329522b229.tar.gz
    sha256: ca93909b693a9550b44c32902f36e87208fa02cd3a46ecbaaeb4185f48ed1390
    target_directory: cmake-renode-infrastructure
  - url: https://github.com/antmicro/tlib/archive/69fff75a0eba7471283b0b8db2e55e8388e284f6.tar.gz
    sha256: e1aa28f2f486888cee76c80d350d5d21b20b1662a05735297730a06edaa04fa8
    target_directory: cmake-tlib

build:
  number: 1

requirements:
  build:
    - cmake
    - ninja
    - if: unix
      then:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - coreutils
        - sed
        - tar
      else:
        - ${{ compiler('m2w64_c') }}
        - ${{ compiler('m2w64_cxx') }}
        - ${{ stdlib('m2w64_c') }}
        - git
        - m2-base
        - m2-bash
        - m2-findutils
        - m2-sed
        - m2-tar

tests:
  - package_contents:
      files:
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-arm-be.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-arm-le.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-arm-m-be.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-arm-m-le.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-arm64-le.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-i386-le.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-ppc-be.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-ppc-le.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-ppc64-be.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-ppc64-le.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-riscv-le.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-riscv64-le.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-sparc-be.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-sparc-le.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-x86_64-le.so
        - ${{ "Library/bin/" if not unix else "lib/" }}renode-cores/translate-xtensa-le.so

about:
  homepage: https://github.com/renode/renode
  summary: "Antmicro's open source simulation and virtual development framework for complex embedded systems"
  description: |
    Renode was created by Antmicro as a virtual development tool for multi-node
    embedded networks (both wired and wireless) and is intended to enable a scalable
    workflow for creating effective, tested and secure IoT systems.

    With Renode, developing, testing, debugging and simulating unmodified software
    for IoT devices is fast, cost-effective and reliable.
  license: MIT
  license_file:
    - LICENSE
    - tlib-LICENSE
    - softfloat-3-COPYING.txt
  documentation: https://renode.io/
  repository: https://github.com/renode/renode

extra:
  recipe-maintainers:
    - MementoRC
    - danielnachun
